# Generated by Django 6.0 on 2026-02-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_no', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='회차')),
                ('draw_date', models.DateField(verbose_name='추첨일')),
                ('number_1', models.PositiveSmallIntegerField()),
                ('number_2', models.PositiveSmallIntegerField()),
                ('number_3', models.PositiveSmallIntegerField()),
                ('number_4', models.PositiveSmallIntegerField()),
                ('number_5', models.PositiveSmallIntegerField()),
                ('number_6', models.PositiveSmallIntegerField()),
                ('bonus_number', models.PositiveSmallIntegerField(verbose_name='보너스')),
                ('first_prize_amount', models.BigIntegerField(default=0, verbose_name='1등 당첨금')),
                ('first_prize_winners', models.PositiveIntegerField(default=0, verbose_name='1등 당첨자수')),
                ('total_sales', models.BigIntegerField(default=0, verbose_name='총 판매금액')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '추첨 결과',
                'verbose_name_plural': '추첨 결과',
                'ordering': ['-draw_no'],
                'get_latest_by': 'draw_no',
            },
        ),
    ]
