# Generated by Django 6.0 on 2026-02-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawresult',
            name='second_prize_amount',
            field=models.BigIntegerField(default=0, verbose_name='2등 당첨금'),
        ),
        migrations.AddField(
            model_name='drawresult',
            name='second_prize_winners',
            field=models.PositiveIntegerField(default=0, verbose_name='2등 당첨자수'),
        ),
    ]
